'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, Globe2, Loader2, MapPin, UserRound } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

export default function NewProspect(){
 const router=useRouter(); const [form,setForm]=useState({business_name:'',business_type:'',contact_name:'',contact_email:'',contact_phone:'',location:'',urls:''}); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 function set(k:keyof typeof form,v:string){setForm(x=>({...x,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/prospects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,urls:form.urls.split(/[\s,]+/).filter(Boolean)})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not create prospect');router.push(`/prospects/${j.prospect.id}`)}catch(e){setError(e instanceof Error?e.message:'Could not create prospect')}finally{setBusy(false)}}
 return <><div className="page-head"><div><Link href="/prospects" className="btn secondary" style={{marginBottom:12}}><ArrowLeft size={14}/> Back to prospects</Link><p className="eyebrow">Pipeline · New</p><h1>Create prospect</h1><p className="page-subtitle">Capture the business details and online sources you want the AI to analyze.</p></div></div>
 <form onSubmit={save}><section className="card"><div className="card-header"><div><h2>Business information</h2><p>Basic context used throughout the proposal workflow.</p></div></div><div className="card-body"><div className="form-grid"><Field label="Business name" required><input className="input" required placeholder="e.g. Apex Fitness Studio" value={form.business_name} onChange={e=>set('business_name',e.target.value)}/></Field><Field label="Business type"><input className="input" placeholder="e.g. Gym, agency, restaurant" value={form.business_type} onChange={e=>set('business_type',e.target.value)}/></Field><Field label="Contact name"><div style={{position:'relative'}}><UserRound size={15} color="#98a2b3" style={{position:'absolute',left:11,top:12}}/><input className="input" style={{paddingLeft:34}} placeholder="Decision maker" value={form.contact_name} onChange={e=>set('contact_name',e.target.value)}/></div></Field><Field label="Location"><div style={{position:'relative'}}><MapPin size={15} color="#98a2b3" style={{position:'absolute',left:11,top:12}}/><input className="input" style={{paddingLeft:34}} placeholder="City / area" value={form.location} onChange={e=>set('location',e.target.value)}/></div></Field><Field label="Email"><input className="input" type="email" placeholder="contact@business.com" value={form.contact_email} onChange={e=>set('contact_email',e.target.value)}/></Field><Field label="Phone"><input className="input" placeholder="+92 …" value={form.contact_phone} onChange={e=>set('contact_phone',e.target.value)}/></Field><Field label="Website & social URLs" full><div style={{position:'relative'}}><Globe2 size={15} color="#98a2b3" style={{position:'absolute',left:11,top:12}}/><textarea className="textarea" style={{paddingLeft:34,minHeight:120}} placeholder={'https://example.com\nhttps://instagram.com/example\nhttps://facebook.com/example'} value={form.urls} onChange={e=>set('urls',e.target.value)}/></div><span className="field-hint">One URL per line or separated by spaces. Include the website and social profiles you want analyzed.</span></Field></div>{error&&<div className="error-box">{error}</div>}<div className="form-footer"><Link className="btn secondary" href="/prospects">Cancel</Link><button className="btn" disabled={busy}>{busy?<Loader2 size={15}/>:<ArrowRight size={15}/>} {busy?'Creating…':'Create prospect'}</button></div></div></section></form></>;
}
function Field({label,required,full,children}:{label:string;required?:boolean;full?:boolean;children:React.ReactNode}){return <div className={`field ${full?'full':''}`}><label>{label}{required?' *':''}</label>{children}</div>}
