'use client';

import Link from 'next/link';
import { ArrowLeft, Check, FileText, Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

type Proposal={id:string;title:string;content:any;status:string;version_number:number;created_at:string;updated_at:string;selected_settings?:any};
export default function ProposalPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [items,setItems]=useState<Proposal[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{params.then(x=>{setId(x.id);load(x.id)})},[params]);
 async function load(pid=id){if(!pid)return;const r=await fetch(`/api/prospects/${pid}/proposals`);const j=await r.json();setItems(j.proposals||[])}
 async function gen(){setBusy(true);setError('');try{const r=await fetch(`/api/prospects/${id}/proposals`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settings:{tone:'Professional',length:'medium',personalizationLevel:'high'}})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Generation failed');await load()}catch(e){setError(e instanceof Error?e.message:'Generation failed')}finally{setBusy(false)}}
 const p=items[0]; const content=p?.content||{};
 return <><div className="page-head"><div><Link href={`/prospects/${id}`} className="btn secondary" style={{marginBottom:12}}><ArrowLeft size={14}/> Back to prospect</Link><p className="eyebrow">Proposal studio</p><h1>Proposals</h1><p className="page-subtitle">Generate and review tailored proposals for this prospect.</p></div><div className="page-actions"><button className="btn secondary" onClick={()=>load()}><RefreshCw size={14}/> Refresh</button><button className="btn" onClick={gen} disabled={busy}>{busy?<Loader2 size={15}/>:<Sparkles size={15}/>} {busy?'Generating…':'Generate proposal'}</button></div></div>
 {error&&<div className="error-box" style={{marginBottom:16}}>{error}</div>}
 {p?<div className="proposal-layout"><article className="card proposal-paper"><div className="badge primary" style={{marginBottom:12}}>Version {p.version_number} · {p.status}</div><div className="proposal-title">{content.title||p.title||'Business Proposal'}</div><div className="entity-sub" style={{marginTop:6}}>Generated {new Date(p.created_at).toLocaleString()}</div>{content.understanding&&<Block title="Understanding">{content.understanding}</Block>}{content.problems&&<Block title="Problems & opportunities">{content.problems}</Block>}{content.solution&&<Block title="Recommended solution">{content.solution}</Block>}{content.deliverables&&<Block title="Deliverables">{Array.isArray(content.deliverables)?<ul>{content.deliverables.map((x:any,i:number)=><li key={i}>{x}</li>)}</ul>:content.deliverables}</Block>}{content.benefits&&<Block title="Benefits">{Array.isArray(content.benefits)?<ul>{content.benefits.map((x:any,i:number)=><li key={i}>{x}</li>)}</ul>:content.benefits}</Block>}{content.timeline&&<Block title="Timeline">{content.timeline}</Block>}{content.investment&&<Block title="Investment">{typeof content.investment==='object'?<pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit'}}>{JSON.stringify(content.investment,null,2)}</pre>:content.investment}</Block>}{content.cta&&<Block title="Call to action">{content.cta}</Block>}<div className="success-box" style={{marginTop:22}}><Check size={14} style={{verticalAlign:'middle',marginRight:5}}/> Proposal is stored in your workspace.</div></article><aside className="card settings-panel"><h3>Proposal details</h3><div className="setting-row"><label>STATUS</label><span className="badge primary">{p.status}</span></div><div className="setting-row"><label>VERSION</label><strong>{p.version_number}</strong></div><div className="setting-row"><label>TONE</label><span>{p.selected_settings?.tone||'Professional'}</span></div><div className="setting-row"><label>LENGTH</label><span>{p.selected_settings?.length||'Medium'}</span></div><div className="setting-row"><label>PERSONALIZATION</label><span>{p.selected_settings?.personalizationLevel||'High'}</span></div></aside></div>:<section className="card"><div className="empty"><FileText size={28} color="#98a2b3"/><strong style={{marginTop:8}}>No proposal yet</strong><p>Generate the first proposal from this prospect.</p><button className="btn" onClick={gen} disabled={busy}><Sparkles size={15}/> Generate proposal</button></div></section>}
 </>;
}
function Block({title,children}:{title:string;children:any}){return <section className="proposal-block"><h3>{title}</h3>{typeof children==='string'?<p>{children}</p>:children}</section>}
